import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';

test('activity filters select tracks and explicitly scope GPS coverage', async ({ page }) => {
  const headers = { Authorization: 'Bearer web-synthetic-filters' };
  async function upload(name: string, row: number, offsets: number[], day: string | null, type: string | null) {
    const points = offsets.map((offset, index) => `<trkpt lat="${51.044 + row * .002}" lon="${3.716 + offset * .004}">${day ? `<time>${day}T08:00:0${index}Z</time>` : ''}</trkpt>`).join('');
    const response = await page.request.post('/api/uploads', { headers, multipart: { file: { name: name + '.gpx', mimeType: 'application/gpx+xml', buffer: Buffer.from(`<gpx version="1.1"><trk><name>${name}</name>${type ? `<type>${type}</type>` : ''}<trkseg>${points}</trkseg></trk></gpx>`) } } });
    expect(response.status()).toBe(202);
    const job = await response.json();
    await expect.poll(async () => (await (await page.request.get(`/api/uploads/${job.id}`, { headers })).json()).status).toBe('succeeded');
    await expect.poll(async () => (await (await page.request.get('/api/progress', { headers })).json()).state).toBe('ready');
  }
  await upload('Earlier walking', 0, [0, 1, 2, 3, 4], '2026-10-05', 'walking');
  await upload('Latest running', 2, [0, 1, 2], '2026-10-06', 'running');
  await upload('Undated outing', 1, [0, 1], null, null);
  const fit = await page.request.post('/api/uploads', { headers, multipart: { file: { name: 'synthetic.fit', mimeType: 'application/octet-stream', buffer: readFileSync('tests/.fixtures/browser.fit') } } });
  expect(fit.status()).toBe(202); const fitJob = await fit.json();
  await expect.poll(async () => (await (await page.request.get(`/api/uploads/${fitJob.id}`, { headers })).json()).status).toBe('succeeded');
  await expect.poll(async () => (await (await page.request.get('/api/progress', { headers })).json()).state).toBe('ready');
  await page.goto('/'); await page.evaluate(() => sessionStorage.setItem('city-runner.session', 'web-synthetic-filters')); await page.reload();
  await page.getByRole('button', { name: 'Activities', exact: true }).click();
  await expect(page.locator('.activity-row')).toHaveCount(4);
  const controls = page.getByRole('region', { name: 'Activity and map filters' });
  await controls.locator('summary').click();
  await controls.getByLabel('Activity start date').fill('2026-10-06');
  await controls.getByLabel('Activity end date').fill('2026-10-06');
  await controls.getByLabel('Activity type', { exact: true }).selectOption('running');
  await controls.getByLabel('File source').selectOption('gpx');
  await controls.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page.locator('.activity-row')).toHaveCount(1);
  await expect(page.locator('.activity-row')).toContainText('Latest running');
  await expect(controls.locator('.filter-summary')).toContainText('Lifetime GPS coverage');
  await controls.getByLabel('Map coverage').selectOption('filtered');
  const filteredProgress = page.waitForResponse((response) => response.ok() && response.url().includes('/api/progress?') && new URL(response.url()).searchParams.get('coverage_scope') === 'filtered');
  await controls.getByRole('button', { name: 'Apply filters' }).click();
  expect((await (await filteredProgress).json()).datasets[0].visited_node_count).toBe(3);
  await expect(page.locator('.map-heading')).toContainText('Selected activities’ GPS coverage');
  const query = 'bbox=3.71,51.04,3.74,51.065&zoom=16&date_from=2026-10-06&date_to=2026-10-06&activity_type=running&source=gpx';
  const selected = await (await page.request.get('/api/map?' + query + '&coverage_scope=filtered', { headers })).json();
  const lifetime = await (await page.request.get('/api/map?' + query, { headers })).json();
  expect(selected.tracks).toHaveLength(1); expect(lifetime.tracks).toHaveLength(1);
  expect(selected.missing_nodes).toHaveLength(37); expect(lifetime.missing_nodes).toHaveLength(25);
  await controls.getByRole('button', { name: 'Reset filters' }).click();
  await expect(page.locator('.activity-row')).toHaveCount(4);
  await controls.getByLabel('File source').selectOption('fit');
  await controls.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page.locator('.activity-row')).toHaveCount(1);
  await controls.getByRole('button', { name: 'Reset filters' }).click();
  await controls.getByLabel('Activity type', { exact: true }).selectOption('unknown');
  await controls.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page.locator('.activity-row')).toHaveCount(1);
  await expect(page.locator('.activity-row')).toContainText('Undated outing');
  await controls.getByLabel('Activity start date').fill('2026-10-06');
  await controls.getByLabel('Activity end date').fill('2026-10-05');
  await controls.getByRole('button', { name: 'Apply filters' }).click();
  await expect(controls.getByRole('alert')).toContainText('end date');
  const isolated = await (await page.request.get('/api/activities/filters', { headers: { Authorization: 'Bearer web-synthetic-view-other' } })).json();
  expect(isolated.activity_types).toEqual([]);
});

test('location, account-scoped viewport and offline recovery use the real browser', async ({ page, context }) => {
  await context.grantPermissions(['geolocation']);
  await context.setGeolocation({ longitude: 3.724, latitude: 51.05, accuracy: 6 });
  await page.goto('/'); await page.evaluate(() => sessionStorage.setItem('city-runner.session', 'web-synthetic-usability')); await page.reload();
  await expect(page.locator('.map-area')).toHaveAttribute('data-ready', 'true');
  const location = page.getByRole('button', { name: 'Show current location' });
  await location.click(); await expect(page.locator('.map-area')).toHaveAttribute('data-located', 'true');
  await expect(page.locator('.map-location')).toContainText('Your location · ±6 m');
  const key = 'city-runner.viewport.web-test-usability';
  await expect.poll(() => page.evaluate((key) => JSON.parse(localStorage.getItem(key) ?? '{}').zoom, key)).toBe(17);
  const saved = await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!), key);
  expect(saved.center[0]).toBeCloseTo(3.724); expect(saved.center[1]).toBeCloseTo(51.05);
  expect(Object.keys(saved).sort()).toEqual(['center', 'zoom']);
  const restoredView = page.waitForResponse((response) => response.ok() && response.url().includes('/api/map?') && Number(new URL(response.url()).searchParams.get('zoom')) === 17);
  await page.reload(); await restoredView; await expect(page.locator('.map-area')).toHaveAttribute('data-ready', 'true');
  await expect(page.locator('.map-area')).toHaveAttribute('data-located', 'false');
  await expect.poll(() => page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).zoom, key)).toBe(17);
  const controls = page.getByRole('region', { name: 'Activity and map filters' });
  await controls.locator('summary').click(); await controls.getByLabel('File source').selectOption('fit'); await controls.getByLabel('Map coverage').selectOption('filtered');
  await controls.getByRole('button', { name: 'Apply filters' }).click();
  await expect(page.locator('.map-message')).toContainText('Coverage uses');
  await page.getByRole('button', { name: 'Find missing nodes', exact: true }).click();
  await expect(page.locator('.hunter-list .node-row').first()).toBeVisible();
  await expect(page.getByRole('region', { name: 'Node Hunter' })).toContainText('missing in this selection');
  await context.setOffline(true);
  await expect(page.locator('.connection-status')).toContainText('You’re offline');
  await expect(page.locator('.connection-status')).toContainText('last loaded progress');
  await expect(page.locator('.connection-status button')).toBeDisabled();
  await expect(page.locator('.hunter-list .node-row')).toHaveCount(0);
  const reconnected = page.waitForResponse((response) => response.ok() && response.url().includes('/api/map?') && new URL(response.url()).searchParams.get('source') === 'fit' && new URL(response.url()).searchParams.get('coverage_scope') === 'filtered');
  await context.setOffline(false); await reconnected;
  await expect(page.locator('.connection-status')).toHaveCount(0);
  await expect(controls.locator('.filter-summary')).toContainText('FIT');
  await page.getByRole('button', { name: 'Cities & streets', exact: true }).click();
  await page.getByLabel('Region', { exact: true }).selectOption({ label: 'Demo Region' });
  await page.getByRole('button', { name: /Demo City/ }).click();
  await page.getByRole('button', { name: /Garden Way/ }).click();
  const streetTarget = page.getByRole('button', { name: 'Add remaining node 1 to route', exact: true });
  await expect(streetTarget).toBeEnabled();
  await context.setOffline(true);
  await expect(streetTarget).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Remaining node 1', exact: true })).toBeDisabled();
  await context.setOffline(false);
  await expect(streetTarget).toBeEnabled();
  // Cancelled and signed-out callbacks must never move the map or expose a marker.
  await page.evaluate(() => Object.defineProperty(navigator, 'geolocation', { configurable: true, value: { getCurrentPosition: (success: unknown) => { (window as unknown as { locationSuccess: unknown }).locationSuccess = success; } } }));
  await location.click(); await page.getByRole('button', { name: 'Cancel location' }).click();
  await page.evaluate(() => (window as unknown as { locationSuccess: (position: unknown) => void }).locationSuccess({ coords: { longitude: 3.72, latitude: 51.04, accuracy: 4 } }));
  await expect(page.locator('.map-area')).toHaveAttribute('data-located', 'false');
  await location.click(); await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.evaluate(() => (window as unknown as { locationSuccess: (position: unknown) => void }).locationSuccess({ coords: { longitude: 3.72, latitude: 51.04, accuracy: 4 } }));
  await expect(page.locator('.map-area')).toHaveAttribute('data-located', 'false');
  await page.evaluate(() => sessionStorage.setItem('city-runner.session', 'web-synthetic-view-other')); await page.reload();
  await expect(page.locator('.map-area')).toHaveAttribute('data-ready', 'true');
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem('city-runner.viewport.web-test-view-other') ?? '{}').zoom)).toBe(14.8);
  expect(await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!), key)).toEqual(saved);
  await page.evaluate(() => Object.defineProperty(navigator, 'geolocation', { configurable: true, value: { getCurrentPosition: (_success: unknown, fail: (error: unknown) => void) => fail({ code: 1 }) } }));
  await location.click(); await expect(page.locator('.map-location [role="alert"]')).toContainText('permission denied');
  await page.evaluate(() => Object.defineProperty(navigator, 'geolocation', { configurable: true, value: { getCurrentPosition: (_success: unknown, fail: (error: unknown) => void) => fail({ code: 3 }) } }));
  await location.click(); await expect(page.locator('.map-location [role="alert"]')).toContainText('timed out');
  await page.evaluate(() => Object.defineProperty(navigator, 'geolocation', { configurable: true, value: { getCurrentPosition: () => { throw new Error('Unavailable'); } } }));
  await location.click(); await expect(page.locator('.map-location [role="alert"]')).toContainText('unavailable');
  await page.evaluate(() => Object.defineProperty(navigator, 'geolocation', { configurable: true, value: { getCurrentPosition: (success: (position: unknown) => void) => success({ coords: { longitude: NaN, latitude: 51, accuracy: 4 } }) } }));
  await location.click(); await expect(page.locator('.map-location [role="alert"]')).toContainText('outside the supported');
  await page.clock.install();
  await page.evaluate(() => Object.defineProperty(navigator, 'geolocation', { configurable: true, value: { getCurrentPosition: () => {} } }));
  await location.click(); await page.clock.fastForward(10_001);
  await expect(page.locator('.map-location [role="alert"]')).toContainText('timed out');
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
