"""Versioned, shared OSM geography."""

from alembic import op

revision = "0004_geography"
down_revision = "0003_jobs"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        CREATE TABLE map_datasets (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            region VARCHAR(128) NOT NULL,
            source_timestamp TIMESTAMPTZ NOT NULL,
            source_checksum CHAR(64) NOT NULL,
            eligibility_rule_version VARCHAR(64) NOT NULL,
            selection_key CHAR(64) NOT NULL,
            coverage_mode VARCHAR(16) NOT NULL CHECK (coverage_mode IN ('complete','sampled')),
            coverage_evidence TEXT NOT NULL,
            status VARCHAR(16) NOT NULL DEFAULT 'importing'
                CHECK (status IN ('importing','active','retired')),
            validated_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (region, source_checksum, eligibility_rule_version, selection_key),
            UNIQUE (region, id)
        )
    """)
    op.execute("""
        CREATE UNIQUE INDEX uq_map_datasets_one_active_region
        ON map_datasets (region) WHERE status = 'active'
    """)
    op.execute("""
        CREATE TABLE cities (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            dataset_id BIGINT NOT NULL,
            osm_relation_id BIGINT NOT NULL,
            name TEXT NOT NULL,
            admin_level VARCHAR(16) NOT NULL,
            boundary geometry(MultiPolygon,4326) NOT NULL,
            FOREIGN KEY (dataset_id) REFERENCES map_datasets(id) ON DELETE CASCADE,
            UNIQUE (dataset_id, id),
            UNIQUE (dataset_id, osm_relation_id)
        )
    """)
    op.execute("CREATE INDEX ix_cities_boundary_gist ON cities USING GIST (boundary)")
    op.execute("""
        CREATE TABLE osm_nodes (
            dataset_id BIGINT NOT NULL REFERENCES map_datasets(id) ON DELETE CASCADE,
            osm_node_id BIGINT NOT NULL,
            point geography(Point,4326) NOT NULL,
            PRIMARY KEY (dataset_id, osm_node_id)
        )
    """)
    op.execute("CREATE INDEX ix_osm_nodes_point_gist ON osm_nodes USING GIST (point)")
    op.execute("""
        CREATE TABLE osm_ways (
            dataset_id BIGINT NOT NULL REFERENCES map_datasets(id) ON DELETE CASCADE,
            osm_way_id BIGINT NOT NULL,
            name TEXT NOT NULL,
            tags JSONB NOT NULL,
            geometry geometry(MultiLineString,4326) NOT NULL,
            PRIMARY KEY (dataset_id, osm_way_id)
        )
    """)
    op.execute("CREATE INDEX ix_osm_ways_geometry_gist ON osm_ways USING GIST (geometry)")
    op.execute("""
        CREATE TABLE streets (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            dataset_id BIGINT NOT NULL,
            city_id BIGINT NOT NULL,
            normalized_name TEXT NOT NULL,
            display_name TEXT NOT NULL,
            eligible_node_count INTEGER NOT NULL DEFAULT 0 CHECK (eligible_node_count >= 0),
            FOREIGN KEY (dataset_id, city_id) REFERENCES cities(dataset_id, id) ON DELETE CASCADE,
            UNIQUE (dataset_id, id),
            UNIQUE (dataset_id, city_id, normalized_name)
        )
    """)
    op.execute("CREATE INDEX ix_streets_dataset_city ON streets (dataset_id, city_id, id)")
    op.execute("""
        CREATE TABLE street_ways (
            dataset_id BIGINT NOT NULL,
            street_id BIGINT NOT NULL,
            osm_way_id BIGINT NOT NULL,
            PRIMARY KEY (dataset_id, street_id, osm_way_id),
            FOREIGN KEY (dataset_id, street_id) REFERENCES streets(dataset_id, id) ON DELETE CASCADE,
            FOREIGN KEY (dataset_id, osm_way_id) REFERENCES osm_ways(dataset_id, osm_way_id) ON DELETE CASCADE
        )
    """)
    op.execute("""
        CREATE TABLE street_nodes (
            dataset_id BIGINT NOT NULL,
            street_id BIGINT NOT NULL,
            osm_node_id BIGINT NOT NULL,
            PRIMARY KEY (dataset_id, street_id, osm_node_id),
            FOREIGN KEY (dataset_id, street_id) REFERENCES streets(dataset_id, id) ON DELETE CASCADE,
            FOREIGN KEY (dataset_id, osm_node_id) REFERENCES osm_nodes(dataset_id, osm_node_id) ON DELETE CASCADE
        )
    """)
    op.execute("CREATE INDEX ix_street_nodes_dataset_node ON street_nodes (dataset_id, osm_node_id)")


def downgrade():
    op.execute("DROP TABLE IF EXISTS street_nodes")
    op.execute("DROP TABLE IF EXISTS street_ways")
    op.execute("DROP TABLE IF EXISTS streets")
    op.execute("DROP TABLE IF EXISTS osm_ways")
    op.execute("DROP TABLE IF EXISTS osm_nodes")
    op.execute("DROP TABLE IF EXISTS cities")
    op.execute("DROP INDEX IF EXISTS uq_map_datasets_one_active_region")
    op.execute("DROP TABLE IF EXISTS map_datasets")
